### ISSUE TITLE
bootcfg /metadata endpoint should include query variables

### ISSUE THREAD

**Issue by dghubble** [coreos/coreos-baremetal#182]
In v0.3.0, `/metadata?foo=bar` renders a `plain/text` response with the selectors and metadata of the matched group. Previously, all query parameters were included in the metadata response, but this was replaced in #64 with the thinking that including the selector key/value pairs was sufficient.

It sounds like there is some need to make query parameters (which are not included in machine group metadata or as selectors) available as /metadata. This issue should track possibly adding that feature back.

From Original Issue (https://github.com/coreos/bugs/issues/1262) by @rothgar 
> When writing ignition groups and files I have situations where I need to use values that were passed to bootcfg in the query but are not in the metadata for the matched system.
An example is a default group (no requirements) which does a CoreOS install. During the install I need to make other calls to internal inventory apis with the system $hostname as a unique key. The original query has the value I need (e.g. http://bootcfg/ignition?hostname=foo&metadata=bar)

I'm not opposed to adding this back, but want to understand the need better. @rothgar why not add the hostname to the group metadata? You wish to control that attribute through DNS management?

**Comment by rothgar** [comment]
My specific use case right now is I have an internal api that controls host pxe files. I set a host to pxe boot and install CoreOS. The last step before a reboot is to call the API to disable PXE boot on next reboot.

My PXE boot pulls from http://bootcfg/ipxe?hostname=foo <-returns generic install group

e.g.
`ExecStart=/usr/bin/curl https://pxe-api/delete/$HOSTNAME`

I can't define hostname in the group metadata because it needs to be unique per host. Without this step the host will continually reboot -> pxe boot -> install CoreOS or I have to manually delete the pxe file after the host(s) boot from them. I'd rather it automatically get removed after the install is successful.

**Comment by dghubble** [comment]
Better summary of the updated behavior at https://github.com/coreos/coreos-baremetal/pull/279
