### ISSUE TITLE
Example PXE doesn't work now

### ISSUE THREAD

**Issue by gosharplite** [coreos/coreos-baremetal#192]
I have a working PXE example with CoreOS 899.17.0. The latest PXE example with CoreOS 1032.0.0 is not working. Using the same network environment, the differences are shown below.
```
$ diff pxe.json.OLD pxe.json.NEW
6,7c6,7
< 		"kernel": "/assets/coreos/899.17.0/coreos_production_pxe.vmlinuz",
< 		"initrd": ["/assets/coreos/899.17.0/coreos_production_pxe_image.cpio.gz"],
---
> 		"kernel": "/assets/coreos/1032.0.0/coreos_production_pxe.vmlinuz",
> 		"initrd": ["/assets/coreos/1032.0.0/coreos_production_pxe_image.cpio.gz"],
```
```
$ diff ssh.yaml.OLD ssh.yaml.NEW
2c2,3
< ignition_version: 1
---
> ignition:
>   version: 2.0.0
```
[Screenshot of CoreOS 899.17.0.](https://raw.githubusercontent.com/gosharplite/scrap/master/OLD.png) (working)
[Screenshot of CoreOS 1032.0.0.](https://raw.githubusercontent.com/gosharplite/scrap/master/NEW.png) (not working)

Network environment commands.
```
sudo docker run -p 8080:8080 --rm -v $PWD:/var/lib/bootcfg:Z -v $PWD/groups/pxe:/var/lib/bootcfg/groups:Z quay.io/coreos/bootcfg:v0.3.0 -address=0.0.0.0:8080 -log-level=debug
```
```
sudo docker run --net=host --rm --cap-add=NET_ADMIN quay.io/coreos/dnsmasq -d -q -i eth1 --dhcp-range=10.128.112.18,10.128.112.24 --enable-tftp --tftp-root=/var/lib/tftpboot --dhcp-userclass=set:ipxe,iPXE --dhcp-boot=tag:#ipxe,undionly.kpxe --dhcp-boot=tag:ipxe,http://bootcfg.foo:8080/boot.ipxe --log-queries --log-dhcp --dhcp-option=3,10.128.83.254 --address=/bootcfg.foo/10.128.112.12
```
VM creation command.
```
virt-install --name tony-node1 -u 16e7d8a7-bfa9-428b-9117-363341bb330b --pxe --disk pool=default,size=6 --boot=hd,network --network=bri
dge:vif.112 --ram=1024 --vcpus=1 --os-type=linux --noautoconsole
```

**Comment by gosharplite** [comment]
Example pxe-disk does work out of box ([screenshot](https://raw.githubusercontent.com/gosharplite/scrap/master/pxe-disk.png)).
Its ignition file uses `ignition_version: 1`.
```
$ cat format-disk.yaml 
---
ignition_version: 1
storage:
  disks:
    - device: /dev/sda
      wipe_table: true
      partitions:
        - label: ROOT
          number: 0
  filesystems:
    - device: "/dev/sda1"
      format: "ext4"
      create:
        force: true
        options:
          - "-LROOT"

{{ if .ssh_authorized_keys }}
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        {{ range $element := .ssh_authorized_keys }}
        - {{$element}}
        {{end}}
{{end}}
```

**Comment by gosharplite** [comment]
Back to example PXE, it works if I use below file.
```
$ cat ssh.yaml
---
ignition_version: 1
{{ if .ssh_authorized_keys }}
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        {{ range $element := .ssh_authorized_keys }}
        - {{$element}}
        {{end}}
{{end}}
```
It seems `ignition version 2.0.0` is the problem.

**Comment by dghubble** [comment]
`bootcfg` 682bb72dde (added after v0.3.0) added support for Ignition 1 and 2.0.0 and the `pxe` example was updated to show that. Running `bootcfg` v0.3.0 with the *latest* examples cloned from master, you'll see v0.3.0 does not serve the 2.0.0 Ignition config. This is unrelated to CoreOS version of the network setup.

With `bootcfg` v0.3.0, the examples in the v0.3.0 tagged checkout should work. Sometimes to use a new or updated example on master, the master (latest) `bootcfg` is needed.

I recognize this can be surprising and non-obvious. Perhaps I'll revert this particular change (esp. since lots of folks try `pxe` first). In the general case though, we'd need to queue up changes to examples until a release happens to do something like the Ignition 1 to 2.0.0 change where a feature/change to the service is needed.
