### ISSUE TITLE
create Alpine APK package

### ISSUE THREAD

**Issue by jumanjiman** [coreos/coreos-baremetal#267]
it would be nice to have an APK available in Alpine's "testing" repo since many people are moving utility services to docker-alpine images.

helpful links:

* http://git.alpinelinux.org/cgit/aports/
* http://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management
* http://lists.alpinelinux.org/alpine-aports/summary.html
* https://pkgs.alpinelinux.org/packages

ref:

* https://github.com/coreos/coreos-baremetal/issues/155
* https://github.com/coreos/coreos-baremetal/issues/266

**Comment by dghubble** [comment]
`bootcfg` can be used with rkt or docker with the official image https://quay.io/repository/coreos/bootcfg or using the pre-build binaries.

Some users already run provisioning services directly on a special provisioner host (RHEL/Fedora, Debian, etc.), depending the number of client machines. I'd like to provide distro friendly packages for those use cases. RPM packages are early in line because they'd be useful to us and for several others.

Can you outline your use case? Are you running alpine Linux as a provisioner for your hardware? I ask because each distro is separate work to create and support.

**Comment by dghubble** [comment]
^ ping?

**Comment by dghubble** [comment]
Feel free to re-open if you come back
