### ISSUE TITLE
Proposal: Programatic Asset Management

### ISSUE THREAD

**Issue by danehans** [coreos/coreos-baremetal#286]
## Background
As with other baremetal provisioning systems, coreos-baremetal should provide programmatic management of assets such as an initrd, kernel or operating system image. Currently, a [script](https://github.com/coreos/coreos-baremetal/blob/master/scripts/get-coreos) is run to create the bootcfg asset directory, add CoreOS assets to the directory and verify the authenticity of the assets. Although this works well for a development environment, this approach to managing assets is limited for production use.

## Proposal
Add support for programmatically managing coreos-baremetal assets through the bootcfg grpc client and server. This approach is similar to how Groups, Profiles, etc are managed by coreos-baremetal. Providing programmatic management of assets will simplify a key component of baremetal provisioning and increase the adoption of coreos-baremetal. The following areas should be addressed to add asset management support:

- [ ] Update the [rpcpb package](https://github.com/coreos/coreos-baremetal/tree/master/bootcfg/rpc/rpcpb) to support an Assets Service.
- [ ] Update the bootcfg [rpc package](https://github.com/coreos/coreos-baremetal/tree/master/bootcfg/rpc) to support Assets.
- [ ] Update [serverpb](https://github.com/coreos/coreos-baremetal/tree/master/bootcfg/server/serverpb) and [storagepb](https://github.com/coreos/coreos-baremetal/tree/master/bootcfg/storage/storagepb) packages to support Asset-related rpc messages.
- [ ] Update Profiles to use kernel/initrd key/value pairs from Assets instead of defining them in a Profile.
- [ ] Update the [filestore package](https://github.com/coreos/coreos-baremetal/blob/master/bootcfg/storage/filestore.go) to support Put/Get/List of Assets.
- [ ] Update bootcfg [cli package](https://github.com/coreos/coreos-baremetal/tree/master/bootcfg/cli) to support Asset management.
- [ ] Update the bootcfg [client package](https://github.com/coreos/coreos-baremetal/blob/master/bootcfg/client/client.go) to support the Assets service Client API
- [ ] Update bootcfg [server package](https://github.com/coreos/coreos-baremetal/tree/master/bootcfg/server) to support Asset management

## Implementation Example
An example asset.json used to describe a coreos-baremetal asset.
```
{
  "id": "coreos1053",
  "name": "coreos1053",
  "type": "boot", // additional asset types could be supported in the future such as certs/keys
  "metadata": {
    "signing_key": "signing_key_uri",
    "kernel": "kernel_uri",
    "kernel_sig": "kernel_sig_uri",
    "initrd": "initrd_uri",
    "initrd_sig": "initrd_sig_uri",
    "image":  "image_uri",
    "image_sig":  "image_sig_uri"
  }
}
```

The bootcmd client could issue an "asset create" command, referencing a json file that describes the desired asset for the bootcfg server to create:
```
$ bootcmd asset create -f asset.json
```

The bootcfg server could perform the following based on the bootcmd client "asset create" request message:

- Validate the request message format
- Set the state of the asset to **pending**
- Store the asset information in the assets-path directory.
- Create a sub directory of assets-path based on the ID of the asset.
- Use the metadata values from the asset to construct an http GET request per file.
- Store the file(s) to the asset subdirectory.
- Perform integrity checking to ensure the file(s) were not corrupted during the transfer.
- Set the state of the asset to **ready** or **error**.

The bootcmd client could issue an "asset list" command to obtain a list of assets for the bootcfg endpoint and their associated status:
```
$ bootcmd asset list
ID			ASSET NAME	Type	Status
coreos1053	coreos1053	boot	Pending|Active|Error
```
The bootcmd client could issue an "asset describe" command to obtain the details of a particular asset:
```
$ bootcmd asset describe coreos1053
ID			ASSET NAME	Type	METADATA
coreos1053	coreos1053	"boot"	{"signing_key":"signing_key_uri","kernel":"kernel_uri","kernel_sig":"kernel_sig_uri","initrd":"initrd_uri","initrd_sig":"initrd_sig_uri","image":"image_uri","image_sig":"image_sig_uri"}
```

A Profile should reference the "asset" ID instead of "initrd"/"kernel" key/value pairs. The etcd.json profile would look like:
```
{
  "id": "etcd",
  "name": "etcd",
  "boot": {
    "asset": "coreos1053",
    "cmdline": {
      "coreos.config.url": "http://bootcfg.foo:8080/ignition?uuid=${uuid}&mac=${net0/mac:hexhyp}",
      "coreos.autologin": "",
      "coreos.first_boot": ""
    }
  },
  "cloud_id": "",
  "ignition_id": "etcd.yaml"
}
```

## Asset Status
Each asset should have an associated status. The following are proposed asset statuses:

**Pending**: Bootcfg is in the process of downloading and verifying the integrity of the asset. The bootcfg server should transition an asset from "Pending" to "Error" if the "Ready" status is not achieved within a configurable threshold or if an error is encountered during the process of downloading an asset. 
**Ready**: The asset has passed integrity checks and bootcfg successfully stored the asset in the assets-path/asset directory.
**Error**: Bootcfg encountered an error downloading, integrity checking, storing, etc. the asset.

**Comment by dghubble** [comment]
First, thanks for the detailed thoughts. I'm glad to get feedback on features that would make administrating, deploying, and provisioning CoreOS easier.

`bootcfg` asset serving was originally added to have a default image location during development. Its been ok for small lab environments - since nodes auto-update we fetch new images into `/var/lib/bootcfg` only when we need to bump the "starting" images.

For large production environments, the thinking was that users reference a production proxying cache or image mirror. In production, its likely those services already exist and are configured for how egress is allowed/disallowed. So far, we haven't recommended or documented a particular production setup.

I have some concerns with the proposal this be done by `bootcfg`:

* Is it a requirement to have an API to add/remove images and manage them? Or would you be better served by a cache servive which proxies images as they are needed?

* Cache proxies or image mirrors are complex applications in their own right and seem orthogonal to `bootcfg` itself. It might be best for us to document a recommended setup (say `quay.io/coreos/squid`). This could be similar to how we provide `quay.io/coreos/dnsmasq` and document how to create a PXE network environments for those who don't have anything setup.

* A service which downloads images must be configured to egress the network. If this were build into `bootcfg`, `bootcfg` becomes responsible for this. It currently has no egress requirements.

* Asset status introduces a failure mode that doesn't exist with a cache proxy. With a proxy, the first request for an image downloads it. With a management API you have to create a `bootcfg` resource and deal with pending states.

* State about whether an async download is pending, ready, or errored must be kept somewhere. Probably with a sentinel file to support the FileStore.

* API-driven automatic downloads provide limited security value. `bootcfg` served images must still be treated as untrusted since the image/signature can be compromised together when no human inspects the signature. We might as well just proxy the public images. The `get-coreos` script does the right thing for small scale. It curls the CoreOS images and presents the GPG fingerprint for visual inspection by the human user who is responsible for deciding they trust the fingerprint. Still, image verification and integrity seem best left to the final mile (host).

* I'd personally avoid calling it an "asset" resource (perhaps "images"). The term seems overloaded. I've seen code use "assets" to refer to templates, photos, CSS, TLS credentials, or OS images or some combination and there is already a temptation to chuck anything in `bootcfg`'s assets directory because of the naming (I regret the name). If development work were to be done, I'd scope it to image management rather than asset management.


I've been reluctant to build out `bootcfg` asset serving for those reasons. I believe it is best addressed by a separate application entirely. Organizaitons which outgrown `bootcfg` asset serving can disable it with `-assets-path=""` and refer to a production service. Which brings us to...

Image caching / serving is an important piece of infrastructure. We could recommend and document a particular setup for large production environments and possibly ship a rkt-runnable container. If none of those solutions are viable, then maybe we take on building a service for this purpose, but I think there are good options available.

**Comment by dghubble** [comment]
This could be addressed with named bundles of metadata (e.g. coreos1053) which could be referenced in Groups for re-use. It could play well with changing iPXE and GRUB configs to be just another config template referenced in a Profile. https://github.com/coreos/coreos-baremetal/issues/92

What that might look like:

Group with `metadata_id` reference.

```
{
  "id": "node1",
  "name": "etcd Node 1",
  "profile": "etcd",
  "selector": {
    "mac": "52:54:00:a1:9c:ae"
  },
  "metadata": {
    "etcd_name": "node1",
    "etcd_initial_cluster": "node1=http://172.15.0.21:2380,node2=http://172.15.0.22:2380,node3=http://172.15.0.23:2380"
  },
  "metadata_id": [
    "coreos1053"
  ]
}
```

Bundle of metadata in `/metadata/coreos1053.json`

{
  "id": "coreos1053",
  "name": "coreos1053",
  "type": "boot", // additional asset types could be supported in the future such as certs/keys
  "metadata": {
    "signing_key": "signing_key_uri",
    "kernel": "kernel_uri",
    "kernel_sig": "kernel_sig_uri",
    "initrd": "initrd_uri",
    "initrd_sig": "initrd_sig_uri",
    "image":  "image_uri",
    "image_sig":  "image_sig_uri"
  }
}

An iPXE or GRUB config template then refers to metadata in the usual way {{.kernel_uri}}. This could be useful for more than bundles of image metadata.

**Comment by chancez** [comment]
I do think it would be handy to support file uploads, but I'm unsure of anything more than that in it's simplest form. A cache/proxy could be put in front of bootcfg, but bootcfg could still be the origin/content server in the scenario I'd imagine. 

This doesn't work well if i wanted to run more than one bootcfg server though (although at that point I'd probably not be using it to serve assets).

**Comment by dghubble** [comment]
The point was that bootcfg should not serve as the image origin in large production deployments.

**Comment by danehans** [comment]
@dghubble thanks for all your feedback. I am trying to replace [Foreman](https://theforeman.org/) with coreos-baremetal. Through this process, I'm finding coreos-baremetal to be more inline with the Foreman [Smart Proxy](https://github.com/theforeman/smart-proxy) than Foreman its self. The Smart Proxy [API](http://projects.theforeman.org/projects/smart-proxy/wiki/API) provides a restful API to various sub-systems for provisioning baremetal servers. The Smart Proxy provides a [TFTP Plugin](https://theforeman.org/manuals/1.12/index.html#4.3.9TFTP) to manage files such as OS images on a TFTP server. I need a way to provide similar functionality. I was hoping this functionality could live within coreos-baremetal to be a more suitable Foreman replacement. I will look closer into your proposal and start developing a Plan B.

**Comment by danehans** [comment]
> Is it a requirement to have an API to add/remove images and manage them? Or would you be better served by a cache service which proxies images as they are needed?

It is a requirement, see the details in the Smart Proxy API in my previous comment. If the "Image management" API does not reside within bootcfg, then I need to create a separate service.

A few other bootcfg contributors and I are trying to replace Foreman and are focused on supporting a large, multi-site production deployment. I would like us to work together to make sure bootcfg is successful in this effort.

> Cache proxies or image mirrors are complex applications in their own right and seem orthogonal to bootcfg itself. It might be best for us to document a recommended setup (say quay.io/coreos/squid). This could be similar to how we provide quay.io/coreos/dnsmasq and document how to create a PXE network environments for those who don't have anything setup.

This will not meet the requirements for replacing Foreman Smart Proxy. However, I think your idea can be taken one step further to create an "image manager" application that programmatically manages a proxy such as squid. Bootcfg would need the ability to redirect clients to the proxy URI's for downloading the initrd, kernel, etc identified in the profile metadata bundle id, correct?

Why have metadata bundles referenced by groups instead of profiles? An OS image is something I standardize on across a group of hosts. The profile concept seems to be the place to set boot information across a group of hosts. Do you suggest groups because it already supports metadata?

> I'd personally avoid calling it an "asset" resource (perhaps "images"). 

+1, I was just trying to fit the proposal into an existing bootcfg naming convention.

> Image caching / serving is an important piece of infrastructure. We could recommend and document a particular setup for large production environments and possibly ship a rkt-runnable container.

Documenting and shipping a container-based proxy for image management is a good step in the right direction to address this important piece of baremetal provisioning. As I mentioned above, we do need to programmatically manage images in order to replace Foreman Smart Proxy.

> If none of those solutions are viable, then maybe we take on building a service for this purpose, but I think there are good options available.

I can understand your position not to add image management to bootcfg. I think their's pros and cons with either direction. If you prefer building a separate service, would you like to init a repo under coreos or do you prefer that I create my own repo?

**Comment by dghubble** [comment]
I've spoken with some colleagues. Cache proxies or image mirrors fulfill our requirements and our recommendations for large deployments ([now in docs](https://github.com/coreos/coreos-baremetal/blob/master/Documentation/deployment.md#download-coreos-optional)) which out-grown the `bootcfg` simple asset folder. They're simple, don't require selecting specific images, and just proxy external sources.

> We do need to programmatically manage images in order to replace Foreman Smart Proxy.

If you need an image manager application like that, your best bet is to find or implement a solution which meets your needs. We're not aiming to match features in Foreman Proxy or other systems 1:1 and we don't have the resources to build that when cache proxies are available. A number of new infrastructure services beyond a provisioning service are higher priority for me as well. Fortunately, `bootcfg` doesn't care too much what images you reference (core-os.net, local network cache, etc.), you can reference any HTTP accessible images.

I'll add an issue to the backlog to document or provide a cache proxy container example.

> Why have metadata bundles referenced by groups instead of profiles?

Its an initial idea. You're welcome to define a profile which uses a particular OS image. The intent is that a machine Profile is a re-usable bundle of provisioning configs (templates). Variances between machines (e.g. node name, num disks) are represented in Group metadata. Whether you code the CoreOS channel/version into the profile or not depends on your needs (e.g. do your k8s workers span channels?) - the examples pin it in profiles bc I validate clusters on particular releases.

The feature to improve this could be metadata bundles attached to groups, but later its plausible they could be attached to Profiles (e.g. as defaults).

> OS images on a TFTP server

External to `bootcfg`, a TFTP server just has to chainload PXE firmware to iPXE or EFI by hosting a `undionly.kpxe` or `grub.efi` file. Beyond either of those, images are served over HTTP.

> If you prefer building a separate service

If we did build an image management service, it would most likely be a separate service.

**Comment by danehans** [comment]
Thanks for the feedback and for updating the documentation.  I can understand that you have priorities other than an image service.

Having an example that uses a mirror/proxy would be helpful. I am interested in testing the squid proxy in my bootcfg lab, but I can not find the image you referenced [here](https://go.webex.com/meet/bschumac).

**Comment by dghubble** [comment]
Wrong link?

**Comment by danehans** [comment]
Oops.. I updated the link.

**Comment by dghubble** [comment]
You're right, the squid image isn't published to Quay. Its currently at https://github.com/kbrwn/rkt-squid - we may pick up where that left off to address #297.

**Comment by dghubble** [comment]
I think we've concluded an API for asset management is a non-goal for bootcfg. This raised some important topics around providing Squid setups/docs in #297 and docs for offline cluster creation in #226. You may also be interested in #350 which demo's creating a Kubernetes cluster in a completely offline environment with local Docker and rkt ACI serving.
