### ISSUE TITLE
Vendored go-systemd is behind latest master

### ISSUE THREAD

**Issue by linearregression** [coreos/coreos-baremetal#338]
For example the sdnotify in original repo changes the signature but the on under vendor basically harbors its own version. Is there any plan to merge two versions?

E.g.
https://github.com/coreos/coreos-baremetal/blob/master/vendor/github.com/coreos/go-systemd/daemon/sdnotify.go

https://github.com/coreos/go-systemd/blob/master/daemon/sdnotify.go

**Comment by dghubble** [comment]
What issue are you running into? Dependencies are auto-resolved recursively and pinned, we're not deliberately using the older version.

**Comment by dghubble** [comment]
I'm not sure why the vendored package would affect you directly, but I've updated coreos-cloudinit (which is what depends on go-systemd) since it hasn't been bumped in a while. You'll find the two files you linked match at this moment.

In future, they may diverge again, that's just the nature of vendoring dependencies. Its not a problem in itself.
