### ISSUE TITLE
Instructions for running quay.io/coreos/dnsmasq with fleet

### ISSUE THREAD

**Issue by urzds** [coreos/coreos-baremetal#67]
I am currently trying to run dnsmasq using fleet. For that I am using the [command from the readme](https://github.com/coreos/coreos-baremetal/blob/4d5128c89a081c317a6622f0e2a99c6cffa30d12/contrib/dnsmasq/README.md), adapted to our usecase:
```systemd
[Unit]
Description=Cluster-internal DHCP server
[Service]
ExecStart=/usr/bin/rkt run --net=host --debug quay.io/coreos/dnsmasq -- -d -q --log-queries --log-dhcp --dhcp-range=192.168.10.252,192.168.10.253 --dhcp-host=...,192.168.10.252 --dhcp-host=...5,192.168.10.253
Restart=always
RestartSec=10

[X-Fleet]
MachineMetadata=role=infra
```

The command mentioned in the readme is:
```
sudo rkt --insecure-options=image run dnsmasq.aci --net=metal0 -- -d -q --dhcp-range=172.15.0.50,172.15.0.99 --enable-tftp --tftp-root=/var/lib/tftpboot --dhcp-userclass=set:ipxe,iPXE --dhcp-boot=tag:#ipxe,undionly.kpxe --dhcp-boot=tag:ipxe,http://bootcfg.foo:8080/boot.ipxe --log-queries --log-dhcp --dhcp-option=3,172.15.0.1 --address=/bootcfg.foo/172.15.0.2
```

I did not use the boot and tftp options, because I just want to run a minimal DHCP server for the moment. Issues with this command as presented in the readme:
* `--insecure-options=image` is not necessary. The image appears to be signed.
* `--net=metal0` does not work, because the network is unknown to rkt.
  - `--net=default` does not work either, because then the service will not be available. That's kind of expected.
  - `--net=host` does not work, because that causes messages like the following:
```
rkt[$PID]: [$UPTIME] dnsmasq[4]: dnsmasq-dhcp: ARP-cache injection failed: Operation not permitted
```
    It is unclear what exactly causes this. It shouldn't be caused by a missing `CAP_NET_ADMIN`, because the container is built with that (see the `build-aci` file).
    I tried to mitigate that by using the `stage1-fly` stage 1 ACI, but the instructions in https://coreos.com/rkt/docs/latest/running-fly-stage1.html seem to be so outdated (`--stage1-path` ,`...-name` and so on are unavailable in the version of Rkt (0.13.0) shipped with current beta CoreOS images (899.7.0) and `--stage1-image` appears unable to download the image from `coreos.com/rkt/stage1-fly` and also using a `/local/path`.

It would be great if an example fleet service file could be provided and the instructions be updated to reflect the currently available versions (alpha, beta, stable) of CoreOS.

**Comment by dghubble** [comment]
For a moment let's backup and just cover running the ACI with rkt - use in a systemd unit or with fleet shouldn't matter here.

Quay.io provides a Docker registry of Docker images (not ACIs). If rkt is asked to fetch a Docker image, it transparently converts the Docker image to an ACI using [docker2aci](https://github.com/appc/docker2aci). Normally rkt seamlessly runs the converted image.

Running `dnsmasq` in a container requires the CAP_NET_ADMIN capabilities (low port number use). Docker treats capabilities as a runtime argument so the Docker image contains nothing about the capabilities that are needed. The produced ACI therefore cannot contain the required capability.

In rkt (actually the appc ACI spec), capabilities are part of the ACI image.

One option is to modify the ACI produced from the Docker image. An easier option (imo) is to build a proper ACI using `build-aci`. The [README](https://github.com/coreos/coreos-baremetal/tree/master/contrib/dnsmasq) shows how to build the ACI yourself using the `build-aci` script. That's why the rkt run example runs `dnsmasq.aci`.

## Future

This will all "just work" once I get the signed `dnsmasq` ACI produced by `build-aci` hosted on coreos.com/dnsmasq. #61 #69

    sudo rkt run coreos.com/dnsmasq --net=host -- -d -q --dhcp-range=172.15.0.50,172.15.0.99 --log-queries --log-dhcp

There are a few internal tasks before that can be done right, so next week is a reasonable estimate.

## Misc

The produced image is indeed not signed and `--insecure-options=image` is needed, unless you sign the `dnsmasq.aci` file yourself.

The `metal0` network should be [created](https://github.com/coreos/coreos-baremetal/blob/master/Documentation/getting-started-rkt.md) for using `bootcfg` to test network booting virtual hardware. Since you say you just want a plain DHCP server, I'm guessing that's not what you're doing.

**Comment by urzds** [comment]
> Quay.io provides a Docker registry of Docker images (not ACIs).

Ah, I assumed it would provide both variants.

> An easier option (imo) is to build a proper ACI using build-aci. The README shows how to build the ACI yourself using the build-aci script. That's why the rkt run example runs dnsmasq.aci.

Ok, I'll try that. I assumed it's a relict from when Rkt did not support fetching images from remote.

> The produced image is indeed not signed, so --insecure-options=image is needed, unless you sign the local dnsmasq.aci file yourself with a trusted key.

I'm a bit confused. Rkt runs the image without any complaints...

> The metal0 network should be created for using bootcfg to test network booting virtual hardware. Since you say you just want a plain DHCP server, I'm guessing that's not what you're doing.

Not right now. Currently I am just using this server to get access to our external storage device. Today or tomorrow the (physical) CoreOS machines will follow.

**Comment by dghubble** [comment]
> Ok, I'll try that. I assumed it's a relict from when Rkt did not support fetching images from remote.

It is intentional in this case, since the hosted Docker image does not contain all the information needed to define ACI for this particular application (`dnsmasq`). 

> I'm a bit confused. Rkt runs the image without any complaints...

Building and running the ACI, will look for `dnsmasq.aci.asc` which is missing. Unless you sign the image (easy enough to do), you'll need the `--insecure-options=image`.

    sudo rkt run --net=host dnsmasq.aci -- -d -q --log-queries --log-dhcp

You're running the Docker image -> ACI from Quay, different story. Docker images are unsigned, so you're probably wondering how the converted image is trusted in any way. Quay signs those with the Quay.io ACI Conversion signing key, which you chose to trust the first time you fetch.

    sudo rkt run --net=host --debug quay.io/coreos/dnsmasq -- -d -q --log-queries --log-dhcp

Try deleting the ACI from `rkt image list` and retrying to see the trust prompt. To be clear, for Docker images, the Quay signature just gives you confidence that Quay did the conversion, it doesn't provide any assurances about the Docker image. Check with the rkt and Quay guys if you're concerned about these matters, they probably have better explanations.

> Not right now. Currently I am just using this server to get access to our external storage device. Today or tomorrow the (physical) CoreOS machines will follow.

If you're booting physical hosts, you'll want to use `--net=host`. `--net=metal0` is a virtual bridge created locally for testing network booting of *virtual* hardware (libvirt VMs).

**Comment by urzds** [comment]
> If you're booting physical hosts, you'll want to use --net=host. --net=metal0 is a virtual bridge created locally for testing network booting of virtual hardware (libvirt VMs).

I'm surprised. I though this whole repository is about CoreOS on *baremetal*... In contrib/dnsmasq/README.md you explicitly advise to use `--net=metal0`... Same for Documentation/getting-started-rkt.md... (Admittedly, in the latter it is at least mentioned in the first paragraph, that the tutorial is in fact not about *baremetal*, but about *VMs* - which I lazily skipped.)

**Comment by urzds** [comment]
P.S: Could you also mention in the readme, that one needs to provide dnsmasq with an upstream `--server`, because the one given in `/etc/resolv.conf` of the produced ACI is garbage (pointing to nowhere, probably an artefact of the build environment).

**Comment by dghubble** [comment]
Project description is "for network booting and configuring CoreOS clusters on virtual or physical hardware." It absolutely is for hardware, I use it on clusters myself. The example setups PXE deploy different clusters on libvirt VMs to get you started and familiar with how it works. Deployments on hardware will depend upon details of the network in *your* datacenter and *your* hardware.

 "In this tutorial, we'll run bootcfg to boot and provision a cluster of four VM machines on a CNI bridge (metal0)." <- The Getting Started tutorials make this clear.

`/etc/resolv.conf` is populated from your machine or you can use `--dns` at runtime to change the DNS.

**Comment by urzds** [comment]
> `/etc/resolv.conf` is populated from your machine or you can use `--dns` at runtime to change the DNS. Can you try those and report back?

The following Fleet unit-file works:
```systemd
[Unit]
Description=Cluster-internal DHCP server

[Service]
ExecStart=/usr/bin/rkt run --insecure-options=image --net=host /path/to/dnsmasq.aci -- --no-daemon --log-queries --log-dhcp --no-resolv --server=... --server=... --dhcp-range=... --dhcp-host=...
Restart=always
RestartSec=10

[X-Fleet]
MachineMetadata=...
```

Beware: The switch is called `--server`, not `--dns`: http://linux.die.net/man/8/dnsmasq

If you like, you can include it in the documentation. If you need me to write a paragraph about it / submit a pull-request, please tell me.

---

> This will all "just work" once I get the signed `dnsmasq` ACI produced by `build-aci` hosted on coreos.com/dnsmasq. #61 #69

I'm very much looking forward to that, as it will significantly simplify the distribution process in our case. Maybe you could also think about how to adjust the produced ACI to the problem described in appc/acbuild#153, while you are at it? I.e. the ACI created by `acbuild` will not be generic, because it will contain a build-host-specific `/etc/resolv.conf`.

**Comment by dghubble** [comment]
`--dns` is a rkt run flag. https://github.com/coreos/rkt/blob/56c398396d4e70c256879133ddc5ece42a7dc116/Documentation/networking/dns.md

**Comment by dghubble** [comment]
I think your problem running `coreos/dnsmasq` has been addressed. Feel free to re-open if not. I've added #80 to track adding docs for deployments via systemd and fleet.
