### ISSUE TITLE
Why does the coreos-install.yaml bootcfg work?

### ISSUE THREAD

**Issue by devurandom** [coreos/coreos-baremetal#79]
Disclaimer: I did not actually try whether it *really* works.

With my limited understanding of DHCP, PXE and bootcfg, the coreos-install.yaml bootcfg does the following:
1. Every machine boots the default `coreos-install` spec.
2. That one downloads the "target" spec's ignition config and installs CoreOS using that.
3. It then reboots, which I assume means we start at (1) again...

As I understand it, DHCP has no way of destinguishing the before/after state of installation - in fact DHCP happens totally outside of bootcfg's control in (e.g.) dnsmasq. Thus PXE does not have any additional information, either. Which means it cannot request any specific spec from bootcfg (e.g. using an additional query parameter).

So the only way that I can imagine that could make this work is if bootcfg knew about the state of the machines it booted. But that would require the machine to give an "installation successful" feedback, so bootcfg could take it out of the loop (and e.g. switch the machine over to another spec). I don't see where that happens...

I originally wanted to implement an apiserver for [pixiecore](https://github.com/danderson/pixiecore) that does exactly that:
1. Boot an unknown machine via DHCP and PXE into an installation script.
2. The script reports back after successful installation.
3. The apiserver would blacklist the machine, so it will no longer be PXE booted.
4. The machine would reboot from disk.

When I first looked at your coreos-install examples, I was glad that you apparently did just what I wanted. But I don't yet understand how, as bootcfg appears to be much more static than what I thought I needed.

**Comment by dghubble** [comment]
Boot order is configured to be (1) hard disk (2) LAN boot, for example. On first power-on, machines network boot and use `bootcfg` to perform the CoreOS install to disk. After restarting, each CoreOS machine performs its "first boot" its Ignition (or Cloud-config). This is what is setup in `scripts/libvirt` examples and what we've used on real clusters as well.

Lower level protocols like IPMI let you change BIOS/UEFI settings such as boot order, wipe disks, etc. on a large number of hosts. `bootcfg` doesn't offer tooling for this lower, out of band configuration.

`bootcfg` does not keep state about the machines it has booted. You're right DHCP happens totally outside `bootcfg`'s control and that's an intentional decoupling.

In future, there may be a convenience "discovery" or "finished" reporting (in last 24 hours), but that state isn't needed for the basic install use cases.

**Comment by devurandom** [comment]
Thanks for explaining this! I didn't think of this simple and low-level way to switch between network and disk boot. The ignition config could even contain an `ExecStartPost` in the `coreos-install.service` systemd unit that changes the boot order to disk-first, after running `coreos-install`. I'll whip up a documentation-PR once I have it working and find a few minutes of free time. `ipmitool ... chassis bootdev disk options=persistent` should work, but `... chassis bootparam set bootflag force_disk` could also be correct.

I assume a high-level solution involving a pixiecore-apiserver would have some benefits (it could e.g. store the config and state in etcd, which other tools could use to display a nice UI), but bootcfg's approach should work well for common needs. :)

**Comment by dghubble** [comment]
Yes, `bootcfg` is intended to work as a Pixiecore API server.

Also, there was some further team discussion about this - maintaining data about running instances should be considered in-scope, though a ways off. Disregard what I said about garbage collecting that info after 24 hours. #97

**Comment by devurandom** [comment]
Are there plans to store the bootcfg config in etcd? That approach appears as if it could simplify quite a bit of such a stateful server.

**Comment by dghubble** [comment]
Yep
