### ISSUE TITLE
vendor: Switch from Godeps tool to glide

### ISSUE THREAD

**Issue by dghubble** [coreos/coreos-baremetal#82]
* Remove the Godeps directory
* https://github.com/kardianos/govendor

**Comment by jonboulle** [comment]
Why govendor? I am willing to throw in the towel on godep since there seems to be so much sentiment against it, but could we maybe attempt to standardise on a replacement across CoreOS projects? So far the leading contender seems to be glide.. particularly since some of the other big projects we integrate with (like k8s) are trending that way.

**Comment by dghubble** [comment]
govendor has worked well for me in the past, no other reason. I'd favor us reviewing govendor, glide, etc. and standardizing across CoreOS. I don't have immediate plans to switch yet since it isn't high priority and needs investigation.

**Comment by jonboulle** [comment]
Created coreos/docs#775

**Comment by dghubble** [comment]
Several CoreOS projects have switched to using Glide. I plan to switch this project as well.
